      
spring: 
  datasource: 
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/poi?useUnicode=true&characterEncoding=UTF-8&useReadAheadInput=false&useUnbufferedInput=false&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 
    
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true


